### ISSUE TITLE
Synset.shortest_path_to_root is broken

### ISSUE THREAD

**Issue by wyleyr** [Germanet-sfs/germanetpy#2]
The `Synset.shortest_path_to_root` method appears to always raise a `ValueError` (perhaps due to an off-by-one error?), e.g:
```
>>> GN.get_synset_by_id('s53080').shortest_path_to_root()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "germanetpy/synset.py", line 273, in shortest_path_to_root
    shortest = paths.index(min([len(path) for path in paths]))
ValueError: 7 is not in list
```

**Comment by bencampbell30** [comment]
Fixed in 7ad47919fea79f266b43760c6a8e98d8aca466cc
